- fix in checking is netforking is up.
Changed files:
    wwwoffle.init -> 1.4

diff --git a/wwwoffle.init b/wwwoffle.init
--- a/wwwoffle.init
+++ b/wwwoffle.init
@@ -17,7 +17,10 @@
 [ -f /etc/sysconfig/wwwoffled ] && . /etc/sysconfig/wwwoffled
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Wwwoffle can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
